Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,7 +17,7 @@ jobs:
       run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
 
     - name: Build Docker image
-      run: docker build -t test1:v2.0.1
+      run: docker build -t test1:v2.0.1 .
 
     - name: Push Docker image
       run: docker push test1:v2.0.1
@@ -35,8 +35,8 @@ jobs:
       uses: azure/k8s-set-context@v1
       with:
         method: kubeconfig
-        kubeconfig: ${{ secrets.KUBECONFIG }}
+        kubeconfig: .github\workflows\kubeconfig.yaml
 
     - name: Deploy to Kubernetes
-      run: kubectl apply -f path/to/your/kubernetes/manifests
-
+      run: |
+        kubectl apply -f path/to/your/kubernetes/manifests || { echo "Failed to apply manifests"; kubectl describe pods; kubectl get events --sort-by=.metadata.creationTimestamp; exit 1; }
